name: 1.0.2$(Rev:.r)

variables:
  buildConfiguration: Release

resources:
- repo: self
  clean: true

pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio

steps:
- task: richardfennellBM.BM-VSTS-Versioning-Task.Version-DotNetCoreAssemblies-Task.VersionDotNetCoreAssemblies@2
  displayName: 'Version .NET Core Assemblies'

- task: richardfennellBM.BM-VSTS-Versioning-Task.Version-PowerShellModule-Task.VersionPowerShellModule@2
  displayName: 'Version PowerShell Modules'

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '>=4.3.0'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'

- task: MSBuild@1
  inputs:
    solution: Elasticsearch.Powershell.sln
    platform: Any CPU
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*tests*.dll
     !**\*TestAdapter.dll
     !**\obj\**

#- task: PowerShell@2
#  inputs:
#    targetType: filePath
#    filePath: deploy.ps1

- task: PowerShell@2
  inputs:
    targetType: filePath
    filePath: generate-doc.ps1
